### ISSUE TITLE
Pterodactyl 1.0.1 Issue

### ISSUE THREAD

**Issue by CommissarVoop** [GeyserMC/pterodactyl-stuff#6]
When installing the egg on the panel it does it without a problem, but when you make the server the install script does nothing aka freezes at installing state.

When looking at the install script for Geyser Connect one of the links is a 404 now ( _https://ci.nukkitx.com/job/GeyserMC/job/GeyserConnect/job/$%7BUPDATE_BRANCH%7D/lastSuccessfulBuild/artifact/target/GeyserConnect.jar_ )

**Comment by JohnB17** [comment]
Hi, the "$%7BUPDATE_BRANCH%7D" part of the url (in the install script it is "${UPDATE_BRANCH}") This is because this is a variable, this is the url it actually goes to:
https://ci.nukkitx.com/job/GeyserMC/job/GeyserConnect/job/master/lastSuccessfulBuild/artifact/target/GeyserConnect.jar

As for your issue, have you tried reinstalling?
